---
title: "Hurricane effects on stream chemistry"
format: html
author: "Roshan Andres Nair"
---

# Background
This project recreated Figure 3 from:

Schaefer, Douglas. A., William H. McDowell, Fredrick N. Scatena, and Clyde E. Asbury. 2000. “Effects of Hurricane Disturbance on Stream Water Concentrations and Fluxes in Eight Tropical Forest Watersheds of the Luquillo Experimental Forest, Puerto Rico.” Journal of Tropical Ecology 16 (2): 189–207. https://doi.org/10.1017/s0266467400001358.

# Data
Data is sourced from:

TMcDowell, W. and International Institute of Tropical Forestry(IITF), USDA Forest Service.. 2024. Chemistry of stream water from the Luquillo Mountains ver 4923064. Environmental Data Initiative. https://doi.org/10.6073/pasta/f31349bebdc304f758718f4798d25458.

# Methods
Moving Average Function: Created a function for taking the 9 week moving average for each chemical concentration. First, a table was created containing columns for the site, each chemical, and the start date for each 9 week window. Then, the concentration samples that fell within each 9 week window were averaged by chemical and added to the table. This table was written into a .csv file to plot the figure. 

# Results
```{r}
#| echo: false
#| warning: false

library(tidyverse)

data <- read_csv("../output/clean_data.csv")

# Plotting ---------------------------------------------------------------

data |>
  ggplot(
    mapping = aes(x = window_start, y = Concentration, linetype = Site)
  ) +
  geom_line() +
  theme_bw() +
  facet_grid(vars(Chemical), scales = "free_y", switch = "y") +
  scale_x_date(name = "Year", sec.axis = dup_axis())
```
